// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.notification-template@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const NOTIFICATION_TEMPLATE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const NOTIFICATION_TEMPLATE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_notification_template { () => { "{\"capability_id\":\"lenso.notification-template@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"activate_version\",\"create_version\",\"get_version\",\"list_versions\",\"preview\",\"render\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_notification_template_client { () => { "{\"capability_id\":\"lenso.notification-template@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_notification_template_client { () => { "{\"capability_id\":\"lenso.notification-template@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const ACTIVATE_VERSION_OPERATION: &str = "activate_version";
pub const CREATE_VERSION_OPERATION: &str = "create_version";
pub const GET_VERSION_OPERATION: &str = "get_version";
pub const LIST_VERSIONS_OPERATION: &str = "list_versions";
pub const PREVIEW_OPERATION: &str = "preview";
pub const RENDER_OPERATION: &str = "render";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ActivateVersionRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ActivateVersionResponse {
    #[serde(rename = "active_version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub active_version: String,
    #[serde(rename = "idempotent_replay")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotent_replay: bool,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ActivateVersionError {
    Conflict,
    IdempotencyConflict,
    InvalidRequest,
    MissingVariable,
    NotFound,
    PreconditionFailed,
    Unauthorized,
    UnexpectedVariable,
    UnsafeVariable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateVersionRequest {
    #[serde(rename = "html_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub html_template: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: String,
    #[serde(rename = "subject_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject_template: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "text_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text_template: String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateVersionResponse {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "idempotent_replay")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotent_replay: bool,
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: String,
    #[serde(rename = "renderer_identity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub renderer_identity: String,
    #[serde(rename = "required_variables")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub required_variables: Vec<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "template_digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_digest: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CreateVersionError {
    Conflict,
    IdempotencyConflict,
    InvalidRequest,
    MissingVariable,
    NotFound,
    PreconditionFailed,
    Unauthorized,
    UnexpectedVariable,
    UnsafeVariable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetVersionRequest {
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetVersionResponse {
    #[serde(rename = "active")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub active: bool,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "head_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub head_revision: Option<String>,
    #[serde(rename = "html_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub html_template: String,
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: String,
    #[serde(rename = "renderer_identity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub renderer_identity: String,
    #[serde(rename = "required_variables")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub required_variables: Vec<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "subject_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject_template: String,
    #[serde(rename = "template_digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_digest: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "text_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text_template: String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetVersionError {
    Conflict,
    IdempotencyConflict,
    InvalidRequest,
    MissingVariable,
    NotFound,
    PreconditionFailed,
    Unauthorized,
    UnexpectedVariable,
    UnsafeVariable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListVersionsRequest {
    #[serde(rename = "count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub count: i64,
    #[serde(rename = "start_index")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub start_index: i64,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListVersionsResponse {
    #[serde(rename = "items_per_page")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub items_per_page: i64,
    #[serde(rename = "resources")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resources: Vec<ListVersionsResponseResourcesItem>,
    #[serde(rename = "start_index")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub start_index: i64,
    #[serde(rename = "total_results")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub total_results: i64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListVersionsResponseResourcesItem {
    #[serde(rename = "active")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub active: bool,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "head_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub head_revision: Option<String>,
    #[serde(rename = "html_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub html_template: String,
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: String,
    #[serde(rename = "renderer_identity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub renderer_identity: String,
    #[serde(rename = "required_variables")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub required_variables: Vec<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "subject_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject_template: String,
    #[serde(rename = "template_digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_digest: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "text_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text_template: String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListVersionsError {
    Conflict,
    IdempotencyConflict,
    InvalidRequest,
    MissingVariable,
    NotFound,
    PreconditionFailed,
    Unauthorized,
    UnexpectedVariable,
    UnsafeVariable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PreviewRequest {
    #[serde(rename = "html_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub html_template: String,
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: String,
    #[serde(rename = "subject_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject_template: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "text_template")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text_template: String,
    #[serde(rename = "variables")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub variables: Vec<PreviewRequestVariablesItem>,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PreviewRequestVariablesItem {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PreviewResponse {
    #[serde(rename = "content_digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_digest: String,
    #[serde(rename = "fallback_used")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub fallback_used: bool,
    #[serde(rename = "html")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub html: String,
    #[serde(rename = "renderer_identity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub renderer_identity: String,
    #[serde(rename = "requested_locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requested_locale: String,
    #[serde(rename = "resolved_locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resolved_locale: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
    #[serde(rename = "template_digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_digest: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "text")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text: String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum PreviewError {
    Conflict,
    IdempotencyConflict,
    InvalidRequest,
    MissingVariable,
    NotFound,
    PreconditionFailed,
    Unauthorized,
    UnexpectedVariable,
    UnsafeVariable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderRequest {
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "variables")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub variables: Vec<RenderRequestVariablesItem>,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderRequestVariablesItem {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderResponse {
    #[serde(rename = "content_digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_digest: String,
    #[serde(rename = "fallback_used")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub fallback_used: bool,
    #[serde(rename = "html")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub html: String,
    #[serde(rename = "renderer_identity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub renderer_identity: String,
    #[serde(rename = "requested_locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requested_locale: String,
    #[serde(rename = "resolved_locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resolved_locale: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
    #[serde(rename = "template_digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_digest: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "text")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text: String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RenderError {
    Conflict,
    IdempotencyConflict,
    InvalidRequest,
    MissingVariable,
    NotFound,
    PreconditionFailed,
    Unauthorized,
    UnexpectedVariable,
    UnsafeVariable,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct NotificationTemplateActivateVersion;
impl RequestCapability for NotificationTemplateActivateVersion {
    type Request = ActivateVersionRequest;
    type Response = ActivateVersionResponse;
    type DomainError = ActivateVersionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ACTIVATE_VERSION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<NotificationTemplateRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).activate_version(context, request)
    }
}

#[derive(Debug)]
pub struct NotificationTemplateCreateVersion;
impl RequestCapability for NotificationTemplateCreateVersion {
    type Request = CreateVersionRequest;
    type Response = CreateVersionResponse;
    type DomainError = CreateVersionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CREATE_VERSION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<NotificationTemplateRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).create_version(context, request)
    }
}

#[derive(Debug)]
pub struct NotificationTemplateGetVersion;
impl RequestCapability for NotificationTemplateGetVersion {
    type Request = GetVersionRequest;
    type Response = GetVersionResponse;
    type DomainError = GetVersionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_VERSION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<NotificationTemplateRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_version(context, request)
    }
}

#[derive(Debug)]
pub struct NotificationTemplateListVersions;
impl RequestCapability for NotificationTemplateListVersions {
    type Request = ListVersionsRequest;
    type Response = ListVersionsResponse;
    type DomainError = ListVersionsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_VERSIONS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<NotificationTemplateRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_versions(context, request)
    }
}

#[derive(Debug)]
pub struct NotificationTemplatePreview;
impl RequestCapability for NotificationTemplatePreview {
    type Request = PreviewRequest;
    type Response = PreviewResponse;
    type DomainError = PreviewError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PREVIEW_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<NotificationTemplateRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).preview(context, request)
    }
}

#[derive(Debug)]
pub struct NotificationTemplateRender;
impl RequestCapability for NotificationTemplateRender {
    type Request = RenderRequest;
    type Response = RenderResponse;
    type DomainError = RenderError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RENDER_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<NotificationTemplateRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).render(context, request)
    }
}

impl serde::Serialize for ActivateVersionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::MissingVariable => serializer.serialize_str("missing_variable"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PreconditionFailed => serializer.serialize_str("precondition_failed"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UnexpectedVariable => serializer.serialize_str("unexpected_variable"),
            Self::UnsafeVariable => serializer.serialize_str("unsafe_variable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ActivateVersionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "missing_variable" => Ok(Self::MissingVariable),
                "not_found" => Ok(Self::NotFound),
                "precondition_failed" => Ok(Self::PreconditionFailed),
                "unauthorized" => Ok(Self::Unauthorized),
                "unexpected_variable" => Ok(Self::UnexpectedVariable),
                "unsafe_variable" => Ok(Self::UnsafeVariable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for CreateVersionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::MissingVariable => serializer.serialize_str("missing_variable"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PreconditionFailed => serializer.serialize_str("precondition_failed"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UnexpectedVariable => serializer.serialize_str("unexpected_variable"),
            Self::UnsafeVariable => serializer.serialize_str("unsafe_variable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CreateVersionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "missing_variable" => Ok(Self::MissingVariable),
                "not_found" => Ok(Self::NotFound),
                "precondition_failed" => Ok(Self::PreconditionFailed),
                "unauthorized" => Ok(Self::Unauthorized),
                "unexpected_variable" => Ok(Self::UnexpectedVariable),
                "unsafe_variable" => Ok(Self::UnsafeVariable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetVersionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::MissingVariable => serializer.serialize_str("missing_variable"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PreconditionFailed => serializer.serialize_str("precondition_failed"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UnexpectedVariable => serializer.serialize_str("unexpected_variable"),
            Self::UnsafeVariable => serializer.serialize_str("unsafe_variable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetVersionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "missing_variable" => Ok(Self::MissingVariable),
                "not_found" => Ok(Self::NotFound),
                "precondition_failed" => Ok(Self::PreconditionFailed),
                "unauthorized" => Ok(Self::Unauthorized),
                "unexpected_variable" => Ok(Self::UnexpectedVariable),
                "unsafe_variable" => Ok(Self::UnsafeVariable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListVersionsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::MissingVariable => serializer.serialize_str("missing_variable"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PreconditionFailed => serializer.serialize_str("precondition_failed"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UnexpectedVariable => serializer.serialize_str("unexpected_variable"),
            Self::UnsafeVariable => serializer.serialize_str("unsafe_variable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListVersionsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "missing_variable" => Ok(Self::MissingVariable),
                "not_found" => Ok(Self::NotFound),
                "precondition_failed" => Ok(Self::PreconditionFailed),
                "unauthorized" => Ok(Self::Unauthorized),
                "unexpected_variable" => Ok(Self::UnexpectedVariable),
                "unsafe_variable" => Ok(Self::UnsafeVariable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for PreviewError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::MissingVariable => serializer.serialize_str("missing_variable"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PreconditionFailed => serializer.serialize_str("precondition_failed"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UnexpectedVariable => serializer.serialize_str("unexpected_variable"),
            Self::UnsafeVariable => serializer.serialize_str("unsafe_variable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for PreviewError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "missing_variable" => Ok(Self::MissingVariable),
                "not_found" => Ok(Self::NotFound),
                "precondition_failed" => Ok(Self::PreconditionFailed),
                "unauthorized" => Ok(Self::Unauthorized),
                "unexpected_variable" => Ok(Self::UnexpectedVariable),
                "unsafe_variable" => Ok(Self::UnsafeVariable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RenderError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::MissingVariable => serializer.serialize_str("missing_variable"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PreconditionFailed => serializer.serialize_str("precondition_failed"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UnexpectedVariable => serializer.serialize_str("unexpected_variable"),
            Self::UnsafeVariable => serializer.serialize_str("unsafe_variable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RenderError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "missing_variable" => Ok(Self::MissingVariable),
                "not_found" => Ok(Self::NotFound),
                "precondition_failed" => Ok(Self::PreconditionFailed),
                "unauthorized" => Ok(Self::Unauthorized),
                "unexpected_variable" => Ok(Self::UnexpectedVariable),
                "unsafe_variable" => Ok(Self::UnsafeVariable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_activate_version_request(value: &ActivateVersionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_activate_version_request(wire: &str) -> Result<ActivateVersionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_activate_version_response(value: &ActivateVersionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_activate_version_response(wire: &str) -> Result<ActivateVersionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_activate_version_error(value: &ActivateVersionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_activate_version_error(wire: &str) -> Result<ActivateVersionError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_create_version_request(value: &CreateVersionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_version_request(wire: &str) -> Result<CreateVersionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_version_response(value: &CreateVersionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_version_response(wire: &str) -> Result<CreateVersionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_version_error(value: &CreateVersionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_version_error(wire: &str) -> Result<CreateVersionError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_version_request(value: &GetVersionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_version_request(wire: &str) -> Result<GetVersionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_version_response(value: &GetVersionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_version_response(wire: &str) -> Result<GetVersionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_version_error(value: &GetVersionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_version_error(wire: &str) -> Result<GetVersionError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_versions_request(value: &ListVersionsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_versions_request(wire: &str) -> Result<ListVersionsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_versions_response(value: &ListVersionsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_versions_response(wire: &str) -> Result<ListVersionsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_versions_error(value: &ListVersionsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_versions_error(wire: &str) -> Result<ListVersionsError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_preview_request(value: &PreviewRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_preview_request(wire: &str) -> Result<PreviewRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_preview_response(value: &PreviewResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_preview_response(wire: &str) -> Result<PreviewResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_preview_error(value: &PreviewError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_preview_error(wire: &str) -> Result<PreviewError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_render_request(value: &RenderRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_render_request(wire: &str) -> Result<RenderRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_render_response(value: &RenderResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_render_response(wire: &str) -> Result<RenderResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_render_error(value: &RenderError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_render_error(wire: &str) -> Result<RenderError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoNotificationTemplateActivateVersionResult {
    fn __lenso_into_result(self) -> Result<Result<ActivateVersionResponse, ActivateVersionError>, RuntimeFailure>;
}
impl __LensoIntoNotificationTemplateActivateVersionResult for Result<ActivateVersionResponse, ActivateVersionError> {
    fn __lenso_into_result(self) -> Result<Result<ActivateVersionResponse, ActivateVersionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoNotificationTemplateActivateVersionResult for Result<Result<ActivateVersionResponse, ActivateVersionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ActivateVersionResponse, ActivateVersionError>, RuntimeFailure> { self }
}
impl __LensoIntoNotificationTemplateActivateVersionResult for Result<ActivateVersionResponse, lenso_plugin_authoring::PluginError<ActivateVersionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ActivateVersionResponse, ActivateVersionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoNotificationTemplateActivateVersionResult for Result<ActivateVersionResponse, NotificationTemplateActivateVersionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ActivateVersionResponse, ActivateVersionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(NotificationTemplateActivateVersionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(NotificationTemplateActivateVersionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoNotificationTemplateCreateVersionResult {
    fn __lenso_into_result(self) -> Result<Result<CreateVersionResponse, CreateVersionError>, RuntimeFailure>;
}
impl __LensoIntoNotificationTemplateCreateVersionResult for Result<CreateVersionResponse, CreateVersionError> {
    fn __lenso_into_result(self) -> Result<Result<CreateVersionResponse, CreateVersionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoNotificationTemplateCreateVersionResult for Result<Result<CreateVersionResponse, CreateVersionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CreateVersionResponse, CreateVersionError>, RuntimeFailure> { self }
}
impl __LensoIntoNotificationTemplateCreateVersionResult for Result<CreateVersionResponse, lenso_plugin_authoring::PluginError<CreateVersionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CreateVersionResponse, CreateVersionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoNotificationTemplateCreateVersionResult for Result<CreateVersionResponse, NotificationTemplateCreateVersionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CreateVersionResponse, CreateVersionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(NotificationTemplateCreateVersionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(NotificationTemplateCreateVersionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoNotificationTemplateGetVersionResult {
    fn __lenso_into_result(self) -> Result<Result<GetVersionResponse, GetVersionError>, RuntimeFailure>;
}
impl __LensoIntoNotificationTemplateGetVersionResult for Result<GetVersionResponse, GetVersionError> {
    fn __lenso_into_result(self) -> Result<Result<GetVersionResponse, GetVersionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoNotificationTemplateGetVersionResult for Result<Result<GetVersionResponse, GetVersionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetVersionResponse, GetVersionError>, RuntimeFailure> { self }
}
impl __LensoIntoNotificationTemplateGetVersionResult for Result<GetVersionResponse, lenso_plugin_authoring::PluginError<GetVersionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetVersionResponse, GetVersionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoNotificationTemplateGetVersionResult for Result<GetVersionResponse, NotificationTemplateGetVersionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetVersionResponse, GetVersionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(NotificationTemplateGetVersionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(NotificationTemplateGetVersionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoNotificationTemplateListVersionsResult {
    fn __lenso_into_result(self) -> Result<Result<ListVersionsResponse, ListVersionsError>, RuntimeFailure>;
}
impl __LensoIntoNotificationTemplateListVersionsResult for Result<ListVersionsResponse, ListVersionsError> {
    fn __lenso_into_result(self) -> Result<Result<ListVersionsResponse, ListVersionsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoNotificationTemplateListVersionsResult for Result<Result<ListVersionsResponse, ListVersionsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListVersionsResponse, ListVersionsError>, RuntimeFailure> { self }
}
impl __LensoIntoNotificationTemplateListVersionsResult for Result<ListVersionsResponse, lenso_plugin_authoring::PluginError<ListVersionsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListVersionsResponse, ListVersionsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoNotificationTemplateListVersionsResult for Result<ListVersionsResponse, NotificationTemplateListVersionsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListVersionsResponse, ListVersionsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(NotificationTemplateListVersionsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(NotificationTemplateListVersionsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoNotificationTemplatePreviewResult {
    fn __lenso_into_result(self) -> Result<Result<PreviewResponse, PreviewError>, RuntimeFailure>;
}
impl __LensoIntoNotificationTemplatePreviewResult for Result<PreviewResponse, PreviewError> {
    fn __lenso_into_result(self) -> Result<Result<PreviewResponse, PreviewError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoNotificationTemplatePreviewResult for Result<Result<PreviewResponse, PreviewError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<PreviewResponse, PreviewError>, RuntimeFailure> { self }
}
impl __LensoIntoNotificationTemplatePreviewResult for Result<PreviewResponse, lenso_plugin_authoring::PluginError<PreviewError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<PreviewResponse, PreviewError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoNotificationTemplatePreviewResult for Result<PreviewResponse, NotificationTemplatePreviewInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<PreviewResponse, PreviewError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(NotificationTemplatePreviewInvocationError::Domain(error)) => Ok(Err(error)),
            Err(NotificationTemplatePreviewInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoNotificationTemplateRenderResult {
    fn __lenso_into_result(self) -> Result<Result<RenderResponse, RenderError>, RuntimeFailure>;
}
impl __LensoIntoNotificationTemplateRenderResult for Result<RenderResponse, RenderError> {
    fn __lenso_into_result(self) -> Result<Result<RenderResponse, RenderError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoNotificationTemplateRenderResult for Result<Result<RenderResponse, RenderError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RenderResponse, RenderError>, RuntimeFailure> { self }
}
impl __LensoIntoNotificationTemplateRenderResult for Result<RenderResponse, lenso_plugin_authoring::PluginError<RenderError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RenderResponse, RenderError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoNotificationTemplateRenderResult for Result<RenderResponse, NotificationTemplateRenderInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RenderResponse, RenderError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(NotificationTemplateRenderInvocationError::Domain(error)) => Ok(Err(error)),
            Err(NotificationTemplateRenderInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait NotificationTemplateProvider: fmt::Debug + 'static {
    fn activate_version(&self, context: InvocationContext, request: ActivateVersionRequest) -> NativeRequestFuture<NotificationTemplateActivateVersion>;
    fn create_version(&self, context: InvocationContext, request: CreateVersionRequest) -> NativeRequestFuture<NotificationTemplateCreateVersion>;
    fn get_version(&self, context: InvocationContext, request: GetVersionRequest) -> NativeRequestFuture<NotificationTemplateGetVersion>;
    fn list_versions(&self, context: InvocationContext, request: ListVersionsRequest) -> NativeRequestFuture<NotificationTemplateListVersions>;
    fn preview(&self, context: InvocationContext, request: PreviewRequest) -> NativeRequestFuture<NotificationTemplatePreview>;
    fn render(&self, context: InvocationContext, request: RenderRequest) -> NativeRequestFuture<NotificationTemplateRender>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_notification_template {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportNotificationTemplate;
        impl $crate::NotificationTemplateProvider for $plugin {
        fn activate_version(&self, context: __LensoNativeSupportNotificationTemplate::InvocationContext, request: $crate::ActivateVersionRequest) -> __LensoNativeSupportNotificationTemplate::NativeRequestFuture<$crate::NotificationTemplateActivateVersion> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::activate_version(&plugin, context, request).await;
                $crate::__LensoIntoNotificationTemplateActivateVersionResult::__lenso_into_result(result)
            })
        }
        fn create_version(&self, context: __LensoNativeSupportNotificationTemplate::InvocationContext, request: $crate::CreateVersionRequest) -> __LensoNativeSupportNotificationTemplate::NativeRequestFuture<$crate::NotificationTemplateCreateVersion> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::create_version(&plugin, context, request).await;
                $crate::__LensoIntoNotificationTemplateCreateVersionResult::__lenso_into_result(result)
            })
        }
        fn get_version(&self, context: __LensoNativeSupportNotificationTemplate::InvocationContext, request: $crate::GetVersionRequest) -> __LensoNativeSupportNotificationTemplate::NativeRequestFuture<$crate::NotificationTemplateGetVersion> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_version(&plugin, context, request).await;
                $crate::__LensoIntoNotificationTemplateGetVersionResult::__lenso_into_result(result)
            })
        }
        fn list_versions(&self, context: __LensoNativeSupportNotificationTemplate::InvocationContext, request: $crate::ListVersionsRequest) -> __LensoNativeSupportNotificationTemplate::NativeRequestFuture<$crate::NotificationTemplateListVersions> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_versions(&plugin, context, request).await;
                $crate::__LensoIntoNotificationTemplateListVersionsResult::__lenso_into_result(result)
            })
        }
        fn preview(&self, context: __LensoNativeSupportNotificationTemplate::InvocationContext, request: $crate::PreviewRequest) -> __LensoNativeSupportNotificationTemplate::NativeRequestFuture<$crate::NotificationTemplatePreview> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::preview(&plugin, context, request).await;
                $crate::__LensoIntoNotificationTemplatePreviewResult::__lenso_into_result(result)
            })
        }
        fn render(&self, context: __LensoNativeSupportNotificationTemplate::InvocationContext, request: $crate::RenderRequest) -> __LensoNativeSupportNotificationTemplate::NativeRequestFuture<$crate::NotificationTemplateRender> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::render(&plugin, context, request).await;
                $crate::__LensoIntoNotificationTemplateRenderResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct NotificationTemplateRequestEndpoint { provider: Rc<dyn NotificationTemplateProvider> }

#[derive(Debug)]
pub struct NotificationTemplateEndpoint<P: NotificationTemplateProvider> { provider: Rc<P>, request_endpoint: NotificationTemplateRequestEndpoint }
impl<P: NotificationTemplateProvider> NotificationTemplateEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn NotificationTemplateProvider> = provider.clone();
        Self { provider, request_endpoint: NotificationTemplateRequestEndpoint { provider: request_provider } }
    }
}

impl<P: NotificationTemplateProvider> NativeRequestEndpoint for NotificationTemplateEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        ACTIVATE_VERSION_OPERATION,
        CREATE_VERSION_OPERATION,
        GET_VERSION_OPERATION,
        LIST_VERSIONS_OPERATION,
        PREVIEW_OPERATION,
        RENDER_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            ACTIVATE_VERSION_OPERATION => {
                let Ok(request) = request.downcast::<ActivateVersionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).activate_version(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            CREATE_VERSION_OPERATION => {
                let Ok(request) = request.downcast::<CreateVersionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).create_version(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_VERSION_OPERATION => {
                let Ok(request) = request.downcast::<GetVersionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_version(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_VERSIONS_OPERATION => {
                let Ok(request) = request.downcast::<ListVersionsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_versions(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            PREVIEW_OPERATION => {
                let Ok(request) = request.downcast::<PreviewRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).preview(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RENDER_OPERATION => {
                let Ok(request) = request.downcast::<RenderRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).render(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_notification_template {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::NotificationTemplateEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_notification_template {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_notification_template!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct NotificationTemplateClient {
    activate_version: NativeRequestHandle<NotificationTemplateActivateVersion>,
    create_version: NativeRequestHandle<NotificationTemplateCreateVersion>,
    get_version: NativeRequestHandle<NotificationTemplateGetVersion>,
    list_versions: NativeRequestHandle<NotificationTemplateListVersions>,
    preview: NativeRequestHandle<NotificationTemplatePreview>,
    render: NativeRequestHandle<NotificationTemplateRender>,
}
impl NotificationTemplateClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn activate_version(&self, request: ActivateVersionRequest) -> Result<ActivateVersionResponse, NotificationTemplateActivateVersionInvocationError> {
        self.activate_version.invoke(ACTIVATE_VERSION_OPERATION, request).await
            .map_err(NotificationTemplateActivateVersionInvocationError::Runtime)?
            .map_err(NotificationTemplateActivateVersionInvocationError::Domain)
    }

    pub async fn activate_version_with_context(&self, context: InvocationContext, request: ActivateVersionRequest) -> Result<ActivateVersionResponse, NotificationTemplateActivateVersionInvocationError> {
        self.activate_version.invoke_with_context(ACTIVATE_VERSION_OPERATION, context, request).await
            .map_err(NotificationTemplateActivateVersionInvocationError::Runtime)?
            .map_err(NotificationTemplateActivateVersionInvocationError::Domain)
    }

    pub async fn create_version(&self, request: CreateVersionRequest) -> Result<CreateVersionResponse, NotificationTemplateCreateVersionInvocationError> {
        self.create_version.invoke(CREATE_VERSION_OPERATION, request).await
            .map_err(NotificationTemplateCreateVersionInvocationError::Runtime)?
            .map_err(NotificationTemplateCreateVersionInvocationError::Domain)
    }

    pub async fn create_version_with_context(&self, context: InvocationContext, request: CreateVersionRequest) -> Result<CreateVersionResponse, NotificationTemplateCreateVersionInvocationError> {
        self.create_version.invoke_with_context(CREATE_VERSION_OPERATION, context, request).await
            .map_err(NotificationTemplateCreateVersionInvocationError::Runtime)?
            .map_err(NotificationTemplateCreateVersionInvocationError::Domain)
    }

    pub async fn get_version(&self, request: GetVersionRequest) -> Result<GetVersionResponse, NotificationTemplateGetVersionInvocationError> {
        self.get_version.invoke(GET_VERSION_OPERATION, request).await
            .map_err(NotificationTemplateGetVersionInvocationError::Runtime)?
            .map_err(NotificationTemplateGetVersionInvocationError::Domain)
    }

    pub async fn get_version_with_context(&self, context: InvocationContext, request: GetVersionRequest) -> Result<GetVersionResponse, NotificationTemplateGetVersionInvocationError> {
        self.get_version.invoke_with_context(GET_VERSION_OPERATION, context, request).await
            .map_err(NotificationTemplateGetVersionInvocationError::Runtime)?
            .map_err(NotificationTemplateGetVersionInvocationError::Domain)
    }

    pub async fn list_versions(&self, request: ListVersionsRequest) -> Result<ListVersionsResponse, NotificationTemplateListVersionsInvocationError> {
        self.list_versions.invoke(LIST_VERSIONS_OPERATION, request).await
            .map_err(NotificationTemplateListVersionsInvocationError::Runtime)?
            .map_err(NotificationTemplateListVersionsInvocationError::Domain)
    }

    pub async fn list_versions_with_context(&self, context: InvocationContext, request: ListVersionsRequest) -> Result<ListVersionsResponse, NotificationTemplateListVersionsInvocationError> {
        self.list_versions.invoke_with_context(LIST_VERSIONS_OPERATION, context, request).await
            .map_err(NotificationTemplateListVersionsInvocationError::Runtime)?
            .map_err(NotificationTemplateListVersionsInvocationError::Domain)
    }

    pub async fn preview(&self, request: PreviewRequest) -> Result<PreviewResponse, NotificationTemplatePreviewInvocationError> {
        self.preview.invoke(PREVIEW_OPERATION, request).await
            .map_err(NotificationTemplatePreviewInvocationError::Runtime)?
            .map_err(NotificationTemplatePreviewInvocationError::Domain)
    }

    pub async fn preview_with_context(&self, context: InvocationContext, request: PreviewRequest) -> Result<PreviewResponse, NotificationTemplatePreviewInvocationError> {
        self.preview.invoke_with_context(PREVIEW_OPERATION, context, request).await
            .map_err(NotificationTemplatePreviewInvocationError::Runtime)?
            .map_err(NotificationTemplatePreviewInvocationError::Domain)
    }

    pub async fn render(&self, request: RenderRequest) -> Result<RenderResponse, NotificationTemplateRenderInvocationError> {
        self.render.invoke(RENDER_OPERATION, request).await
            .map_err(NotificationTemplateRenderInvocationError::Runtime)?
            .map_err(NotificationTemplateRenderInvocationError::Domain)
    }

    pub async fn render_with_context(&self, context: InvocationContext, request: RenderRequest) -> Result<RenderResponse, NotificationTemplateRenderInvocationError> {
        self.render.invoke_with_context(RENDER_OPERATION, context, request).await
            .map_err(NotificationTemplateRenderInvocationError::Runtime)?
            .map_err(NotificationTemplateRenderInvocationError::Domain)
    }
}

impl CapabilityClient for NotificationTemplateClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            activate_version: dependencies.one::<NotificationTemplateActivateVersion>()?,
            create_version: dependencies.one::<NotificationTemplateCreateVersion>()?,
            get_version: dependencies.one::<NotificationTemplateGetVersion>()?,
            list_versions: dependencies.one::<NotificationTemplateListVersions>()?,
            preview: dependencies.one::<NotificationTemplatePreview>()?,
            render: dependencies.one::<NotificationTemplateRender>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for NotificationTemplateClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    activate_version: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<NotificationTemplateActivateVersion>()?,
                    create_version: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<NotificationTemplateCreateVersion>()?,
                    get_version: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<NotificationTemplateGetVersion>()?,
                    list_versions: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<NotificationTemplateListVersions>()?,
                    preview: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<NotificationTemplatePreview>()?,
                    render: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<NotificationTemplateRender>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum NotificationTemplateActivateVersionInvocationError {
    Domain(ActivateVersionError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum NotificationTemplateCreateVersionInvocationError {
    Domain(CreateVersionError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum NotificationTemplateGetVersionInvocationError {
    Domain(GetVersionError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum NotificationTemplateListVersionsInvocationError {
    Domain(ListVersionsError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum NotificationTemplatePreviewInvocationError {
    Domain(PreviewError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum NotificationTemplateRenderInvocationError {
    Domain(RenderError),
    Runtime(RuntimeFailure),
}
